name: Dealii

on:
  push:
    paths:
      - 'gcc/*'
      - 'clang/*'
      - '.github/workflows/dealii.yml'
  schedule:
    - cron: '5 2 * * 0'

jobs:

  dealii-build:

    runs-on: ubuntu-latest
    env:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        package: dealii
    strategy:
        matrix:
          include:
            - compiler: gcc
              compiler_version: "11"
              base_image_prefix: "gcc:"
            - compiler: clang
              compiler_version: "14"
              base_image_prefix: "teeks99/clang-ubuntu:"

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build image
        run: |
          docker build ${{ matrix.compiler }} \
          --tag "${{ env.username }}/${{ env.package }}:${{ matrix.compiler }}${{ matrix.compiler_version }}" \
          --tag "${{ env.username }}/${{ env.package }}:${{ matrix.compiler }}" \
          --build-arg "BASE_IMAGE=${{ matrix.base_image_prefix }}${{ matrix.compiler_version }}"

      - name: Push image
        if: github.ref == 'refs/heads/master' && success()
        run: docker push --all-tags "${{ env.username }}/${{ env.package }}"
