name: Dealii-for-dealfem

on:
  push:
    paths:
      - 'for-dealfem-*/**'
      - '.github/workflows/dealii-for-dealfem*'
  schedule:
    - cron: '5 2 * * 0'

jobs:

  dealii-build:

    runs-on: ubuntu-latest
    strategy:
        matrix:
            directory:
              - ubuntu-package-18
              - ubuntu-package
              - for-dealfem
              - for-dealfem-latest-gcc
              - for-dealfem-latest-clang

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build ${{ matrix.directory }} --tag "rrastak/dealii:${{ matrix.directory }}"

      - name: Push image
        if: github.ref == 'refs/heads/master' && success()
        run: |
          echo "${{ secrets.docker_pass }}" | docker login -u rrastak --password-stdin
          docker push "rrastak/dealii:${{ matrix.directory }}"
