name: openMPI

on:
  push:
    paths:
      - 'openmpi-*/Dockerfile'
      - '.github/workflows/openmpi.yml'

jobs:

  mpi-build:

    runs-on: ubuntu-latest
    env:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        package: openmpi
        link: https://download.open-mpi.org/release/open-mpi/v4.1/openmpi-4.1.2.tar.gz
        version: 4.1.2

    strategy:
        matrix:
          include:
            - compiler: gcc
              compiler_version: "10.3"
              compiler_image_prefix: "gcc:"
            - compiler: clang
              compiler_version: "13"
              compiler_image_prefix: "teeks99/clang-ubuntu:"

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build image
        run: |
            docker build openmpi-${{ matrix.compiler }} \
              --tag "${{ env.username }}/${{ env.package }}:${{ env.version }}-${{ matrix.compiler }}${{ matrix.compiler_version }}" \
              --tag "${{ env.username }}/${{ env.package }}:${{ env.version }}-${{ matrix.compiler }}" \
              --tag "${{ env.username }}/${{ env.package }}:${{ matrix.compiler }}" \
              --build-arg MPI_VERSION=${{ env.version }} \
              --build-arg MPI_PACKAGE_LINK=${{ env.link }} \
              --build-arg "BASE_IMAGE=${{ matrix.compiler_image_prefix }}${{ matrix.compiler_version }}"


      - name: Push image
        if: github.ref == 'refs/heads/master' && success()
        run: docker push --all-tags ${{ env.username }}/${{ env.package }}
