name: Trilinos

on:
  push:
    paths:
      trilinos-*/**
      .github/workflows/trilinos*

jobs:

  trilinos-build:

    runs-on: ubuntu-latest
    env:
        link: https://github.com/trilinos/Trilinos/archive/trilinos-release-13-0-0.tar.gz
        version: 13.0.0

    strategy:
        matrix:
            method:
                - gcc
                - clang

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
            docker build trilinos-${{ matrix.method }} \
              --tag "rrastak/trilinos:${{ env.version }}-${{ matrix.method }}" \
              --build-arg TRILINOS_PACKAGE_LINK=${{ env.link }}

      - name: Push image
        if: github.ref == 'refs/heads/master' && success()
        run: |
          echo "${{ secrets.docker_pass }}" | docker login -u rrastak --password-stdin
          docker push "rrastak/trilinos:${{ env.version }}-${{ matrix.method }}"
