name: Trilinos

on:
  push:
    paths:
      - 'trilinos-*/**'
      - '.github/workflows/trilinos*'

jobs:

  trilinos-build:

    runs-on: ubuntu-latest
    env:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_hub_access_token }}
        link: https://github.com/trilinos/Trilinos/archive/trilinos-release-13-0-1.tar.gz
        version: 13.0.1

    strategy:
        matrix:
          include:
            - compiler: gcc
              compiler_version: "10.2"
              mpi: openmpi
              mpi_version: "4.0.5"
            - compiler: clang
              compiler_version: "12"
              mpi: openmpi
              mpi_version: "4.0.5"

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
            docker build trilinos-${{ matrix.compiler }} \
              --tag "${{ env.username }}/trilinos:${{ env.version }}-${{ matrix.mpi }}${{ matrix.mpi_version }}-${{ matrix.compiler }}${{ matrix.compiler_version }}" \
              --tag "${{ env.username }}/trilinos:${{ env.version }}-${{ matrix.mpi }}${{ matrix.mpi_version }}-${{ matrix.compiler }}" \
              --tag "${{ env.username }}/trilinos:${{ env.version }}-${{ matrix.mpi }}-${{ matrix.compiler }}${{ matrix.compiler_version }}" \
              --tag "${{ env.username }}/trilinos:${{ env.version }}-${{ matrix.mpi }}-${{ matrix.compiler }}" \
              --build-arg TRILINOS_PACKAGE_LINK=${{ env.link }} \
              --build-arg BASE_IMAGE=${{ env.username }}/mpi:${{ matrix.mpi }}.${{ matrix.mpi_version }}-${{ matrix.compiler }}

      - name: Push image
        if: github.ref == 'refs/heads/master' && success()
        run: |
          docker login -u ${{ env.username }} -p ${{ env.password }}
          docker push --all-tags ${{ env.username }}/trilinos
