name: Trilinos

on:
  push:
    paths:
      - 'trilinos-*/**'
      - '.github/workflows/trilinos*'

jobs:

  trilinos-build:

    runs-on: ubuntu-latest
    env:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        link: https://github.com/trilinos/Trilinos/archive/trilinos-release-13-0-1.tar.gz
        version: 13.0.1

    strategy:
        matrix:
          include:
            - compiler: gcc
              compiler_version: "10.2"
              mpi: openmpi
              mpi_version: "4.0.5"
            - compiler: clang
              compiler_version: "12"
              mpi: openmpi
              mpi_version: "4.0.5"

    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build image
        run: |
            docker build trilinos-${{ matrix.compiler }} \
              --tag "${{ env.username }}/trilinos:${{ env.version }}-${{ matrix.mpi }}${{ matrix.mpi_version }}-${{ matrix.compiler }}${{ matrix.compiler_version }}" \
              --tag "${{ env.username }}/trilinos:${{ env.version }}-${{ matrix.mpi }}${{ matrix.mpi_version }}-${{ matrix.compiler }}" \
              --tag "${{ env.username }}/trilinos:${{ env.version }}-${{ matrix.mpi }}-${{ matrix.compiler }}${{ matrix.compiler_version }}" \
              --tag "${{ env.username }}/trilinos:${{ env.version }}-${{ matrix.mpi }}-${{ matrix.compiler }}" \
              --tag "${{ env.username }}/trilinos:${{ matrix.mpi }}-${{ matrix.compiler }}" \
              --tag "${{ env.username }}/trilinos:${{ matrix.compiler }}" \
              --build-arg TRILINOS_PACKAGE_LINK=${{ env.link }} \
              --build-arg BASE_IMAGE=${{ env.username }}/${{ matrix.mpi }}:${{ matrix.mpi_version }}-${{ matrix.compiler }}${{ matrix.compiler_version }}

      - name: Push image
        if: github.ref == 'refs/heads/master' && success()
        run: docker push --all-tags ${{ env.username }}/trilinos
